name: Deploy Lambda Function

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: FiapLumiereMediaProcessorLambda
  DEPENDENCY_LAYER_NAME: VideoExtractorDependencies
  PYTHON_VERSION: '3.9'
  DIST_DIR: dist
  S3_BUCKET: fiap-lumiere-lambda-code-bucket

permissions:
  contents: read
  id-token: write

jobs:
  build-and-test:
    name: Construir Artefato, Executar Testes e Analisar Cobertura
    runs-on: ubuntu-latest

    steps:
      - name: Realizar Checkout do Código-fonte
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Executar testes e gerar cobertura
        run: |
          python -m pytest tests/ -v --cov=src/ --cov-report=xml --cov-report=html

      - name: Analisar com SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=lumiere-fiap-soat-hackaton_fiap-lumiere-extractor-lambda
            -Dsonar.organization=lumiere-fiap-soat-hackaton
            -Dsonar.sources=src
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=**/common/**,**/__test__/**,**/main.py,**/configuration.py
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Validar Quality Gate do SonarCloud
        continue-on-error: true
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Aguardando análise do SonarCloud finalizar..."

          PROJECT_KEY="lumiere-fiap-soat-hackaton_fiap-lumiere-extractor-lambda"
          TASK_ID=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/ce/component?component=$PROJECT_KEY" | jq -r '.queue[0].id')

          if [ -z "$TASK_ID" ] || [ "$TASK_ID" == "null" ]; then
            echo "❌ Não foi possível encontrar o TASK_ID. A análise pode não ter iniciado."
            exit 1
          fi

          STATUS="PENDING"
          while [ "$STATUS" != "SUCCESS" ] && [ "$STATUS" != "FAILED" ]; do
            echo "⏳ Status da análise: $STATUS"
            sleep 5
            STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/ce/task?id=$TASK_ID" | jq -r '.task.status')
          done

          if [ "$STATUS" != "SUCCESS" ]; then
            echo "❌ A análise falhou no SonarCloud (status: $STATUS)"
            exit 1
          fi

          ANALYSIS_ID=""
          while [ -z "$ANALYSIS_ID" ] || [ "$ANALYSIS_ID" == "null" ]; do
            echo "⏳ Aguardando analysisId da task..."
            sleep 3
            ANALYSIS_ID=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/ce/task?id=$TASK_ID" | jq -r '.task.analysisId')
          done

          echo "🔍 Validando Quality Gate para análise $ANALYSIS_ID..."

          QUALITY_GATE_STATUS=$(curl -s -u $SONAR_TOKEN: \
            "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$ANALYSIS_ID" \
            | jq -r '.projectStatus.status')

          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
            echo -e "\n❌ Quality Gate falhou! Detalhes:"
            curl -s -u $SONAR_TOKEN: \
              "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$ANALYSIS_ID" \
              | jq -r '.projectStatus.conditions[] | select(.status != "OK") | "- Critério: \(.metric)\n  Valor atual: \(.actual // \"n/a\")\n  Status: \(.status)\n"'
            echo -e "\n🔗 Ver detalhes: https://sonarcloud.io/dashboard?id=$PROJECT_KEY"
            exit 1
          else
            echo -e "\n✅ Quality Gate aprovado."
          fi

  build-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Lambda Layer e Function
        run: |
          chmod +x bin/deploy.sh
          ./bin/deploy.sh build

      - name: Deploy Lambda Layer e Function
        run: |
          ./bin/deploy.sh deploy

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-deployment-artifacts
          path: |
            ${{ env.DIST_DIR }}/lambda-function.zip
            ${{ env.DIST_DIR }}/lambda-layer.zip
          retention-days: 30